name: Exec Signals Hourly
on:
  schedule:
    - cron: "15 * * * *"
  workflow_dispatch: {}
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install requests
      - run: python exec_signal_scraper.py
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add executive_signals.csv executive_signals.json
          git commit -m "Auto update $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "No changes"
          git push
